comet:
  _target_: lightning.pytorch.loggers.comet.CometLogger
  api_key: ${oc.env:COMET_API_KEY}
  workspace: "mkthoma"
  project_name: "dogbreed-classifier"
  experiment_name: null
  save_dir: "${paths.output_dir}/comet_logs/"
  log_code: True
  log_graph: True
