name: Train Dogbreed Model

on:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/train_dogbreed_model.yml'
      - 'Dockerfile'
      - 'src/**'
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

permissions:
  contents: write
  pull-requests: write

jobs:
  train_model:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: false
        load: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

    - name: Set up Comet ML
      run: |
        echo "COMET_API_KEY=${{ secrets.COMET_API_KEY }}" >> $GITHUB_ENV

    - name: Train model
      run: |
        docker run --name trainer \
          -v ${{ github.workspace }}/logs:/app/logs \
          -v ${{ github.workspace }}/data:/app/data \
          -e COMET_API_KEY=${{ secrets.COMET_API_KEY }} \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            /app/src/train.py trainer.max_epochs=1

    - name: Set permissions for logs directory
      run: sudo chown -R $USER:$USER ${{ github.workspace }}/logs

    - name: Set permissions for model artifacts directory
      run: sudo chown -R $USER:$USER ${{ github.workspace }}/model_artifacts

    - name: Upload model checkpoint
      uses: actions/upload-artifact@v3
      with:
        name: model-checkpoint
        path: logs/train/runs/*/checkpoints/*.ckpt
        if-no-files-found: error

    - name: Generate plots
      run: |
        LOG_FILE=$(find ${{ github.workspace }}/logs/train/runs -name train.log)
        LOG_FILE=${LOG_FILE#${{ github.workspace }}/}
        LOG_FILE="/app/${LOG_FILE}"
        echo "Log file path: $LOG_FILE"

        docker run --rm \
          -v ${{ github.workspace }}/logs:/app/logs \
          -v ${{ github.workspace }}/src:/app/src \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            /app/src/generate_plots.py --log_file_path $LOG_FILE

    - name: Run inference on test images
      run: |
        docker run --rm \
          -v ${{ github.workspace }}/src:/app/src \
          -v ${{ github.workspace }}/model_artifacts:/app/model_artifacts \
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            /app/src/infer.py

    - name: Install CML
      run: |
        npm install -g @dvcorg/cml

    - name: Update CML report with inference results
      env:
        REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "## Model Training Results" >> report.md
        echo "### Performance Metrics" >> report.md
        echo '![Metrics Comparison](./logs/plots/plots/metrics_comparison.png)' >> report.md
        echo "### Inference Results" >> report.md
        echo "Sample predictions from the trained model:" >> report.md
        for image in ./model_artifacts/predicted_images/*.png; do
          echo "![Prediction: ](${image})" >> report.md
        done

    - name: Set permissions for predicted_images directory
      run: sudo chown -R $USER:$USER ${{ github.workspace }}/model_artifacts/predicted_images

    - name: Delete untracked files from predicted_images
      run: |
        git clean -fdx model_artifacts/predicted_images

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7.0.5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Add model training results
        branch: feature/model-training-results
        title: 'Add model training results'
        body: 'This PR includes the latest model training results and updates.'

    - name: Comment on Pull Request
      run: cml comment create report.md

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-training-artifacts
        path: |
          ${{ github.workspace }}/logs/plots/plots/metrics_comparison.png
          report.md
        if-no-files-found: error

    - name: Print success message
      run: echo "Model training and inference completed successfully. Artifacts have been uploaded."
